// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: admin.sql

package DB

import (
	"context"
	"database/sql"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO document (
  documentid,name,createdby
) VALUES (
  $1,$2,$3
)
RETURNING documentid, name, created_at, createdby
`

type CreateDocumentParams struct {
	Documentid int32         `json:"documentid"`
	Name       string        `json:"name"`
	Createdby  sql.NullInt32 `json:"createdby"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.queryRow(ctx, q.createDocumentStmt, createDocument, arg.Documentid, arg.Name, arg.Createdby)
	var i Document
	err := row.Scan(
		&i.Documentid,
		&i.Name,
		&i.CreatedAt,
		&i.Createdby,
	)
	return i, err
}

const createUsers = `-- name: CreateUsers :one
INSERT INTO users (
  id,username,userhash,admin
) VALUES (
  $1,$2,$3,$4
)
RETURNING id, username, userhash, created_at, admin
`

type CreateUsersParams struct {
	ID       int32        `json:"id"`
	Username string       `json:"username"`
	Userhash string       `json:"userhash"`
	Admin    sql.NullBool `json:"admin"`
}

func (q *Queries) CreateUsers(ctx context.Context, arg CreateUsersParams) (User, error) {
	row := q.queryRow(ctx, q.createUsersStmt, createUsers,
		arg.ID,
		arg.Username,
		arg.Userhash,
		arg.Admin,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Userhash,
		&i.CreatedAt,
		&i.Admin,
	)
	return i, err
}

const deleteDocumentAdmin = `-- name: DeleteDocumentAdmin :exec
DELETE FROM document WHERE documentid = $1
`

func (q *Queries) DeleteDocumentAdmin(ctx context.Context, documentid int32) error {
	_, err := q.exec(ctx, q.deleteDocumentAdminStmt, deleteDocumentAdmin, documentid)
	return err
}

const deleteDocumentNormal = `-- name: DeleteDocumentNormal :exec
DELETE FROM document WHERE documentid = $1 AND createdby = $2
`

type DeleteDocumentNormalParams struct {
	Documentid int32         `json:"documentid"`
	Createdby  sql.NullInt32 `json:"createdby"`
}

func (q *Queries) DeleteDocumentNormal(ctx context.Context, arg DeleteDocumentNormalParams) error {
	_, err := q.exec(ctx, q.deleteDocumentNormalStmt, deleteDocumentNormal, arg.Documentid, arg.Createdby)
	return err
}

const deleteusers = `-- name: Deleteusers :exec

DELETE FROM users WHERE id = $1
`

// All Delete operations
func (q *Queries) Deleteusers(ctx context.Context, id int32) error {
	_, err := q.exec(ctx, q.deleteusersStmt, deleteusers, id)
	return err
}

const getDocumentByCreatebyNormal = `-- name: GetDocumentByCreatebyNormal :many
SELECT documentid, name, created_at, createdby FROM document WHERE documentid = $1 AND createdby = $2
`

type GetDocumentByCreatebyNormalParams struct {
	Documentid int32         `json:"documentid"`
	Createdby  sql.NullInt32 `json:"createdby"`
}

func (q *Queries) GetDocumentByCreatebyNormal(ctx context.Context, arg GetDocumentByCreatebyNormalParams) ([]Document, error) {
	rows, err := q.query(ctx, q.getDocumentByCreatebyNormalStmt, getDocumentByCreatebyNormal, arg.Documentid, arg.Createdby)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.Documentid,
			&i.Name,
			&i.CreatedAt,
			&i.Createdby,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDocumentByID = `-- name: GetDocumentByID :many
SELECT documentid, name, created_at, createdby FROM document WHERE documentid = $1
`

func (q *Queries) GetDocumentByID(ctx context.Context, documentid int32) ([]Document, error) {
	rows, err := q.query(ctx, q.getDocumentByIDStmt, getDocumentByID, documentid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.Documentid,
			&i.Name,
			&i.CreatedAt,
			&i.Createdby,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, userhash, created_at, admin FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.queryRow(ctx, q.getUserByIDStmt, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Userhash,
		&i.CreatedAt,
		&i.Admin,
	)
	return i, err
}

const getUserByIDAndAdmin = `-- name: GetUserByIDAndAdmin :one
SELECT id, username, userhash, created_at, admin FROM users WHERE id = $1 AND admin = $2
`

type GetUserByIDAndAdminParams struct {
	ID    int32        `json:"id"`
	Admin sql.NullBool `json:"admin"`
}

// All Get operations
func (q *Queries) GetUserByIDAndAdmin(ctx context.Context, arg GetUserByIDAndAdminParams) (User, error) {
	row := q.queryRow(ctx, q.getUserByIDAndAdminStmt, getUserByIDAndAdmin, arg.ID, arg.Admin)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Userhash,
		&i.CreatedAt,
		&i.Admin,
	)
	return i, err
}

const getUserByNAME = `-- name: GetUserByNAME :many
SELECT id, username, userhash, created_at, admin FROM users WHERE username = $1
`

func (q *Queries) GetUserByNAME(ctx context.Context, username string) ([]User, error) {
	rows, err := q.query(ctx, q.getUserByNAMEStmt, getUserByNAME, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Userhash,
			&i.CreatedAt,
			&i.Admin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUsers = `-- name: UpdateUsers :exec
UPDATE users SET userhash = $1 WHERE id = $2
`

type UpdateUsersParams struct {
	Userhash string `json:"userhash"`
	ID       int32  `json:"id"`
}

// All Update operations
func (q *Queries) UpdateUsers(ctx context.Context, arg UpdateUsersParams) error {
	_, err := q.exec(ctx, q.updateUsersStmt, updateUsers, arg.Userhash, arg.ID)
	return err
}
