// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package DB

import (
	"database/sql"
)

type Document struct {
	Documentid int32         `json:"documentid"`
	Name       string        `json:"name"`
	CreatedAt  sql.NullTime  `json:"created_at"`
	Createdby  sql.NullInt32 `json:"createdby"`
}

type User struct {
	ID        int32        `json:"id"`
	Username  string       `json:"username"`
	Userhash  string       `json:"userhash"`
	CreatedAt sql.NullTime `json:"created_at"`
	Admin     sql.NullBool `json:"admin"`
}
