// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package DB

import (
	"database/sql"
)

type Admin struct {
	ID int32 `json:"id"`
}

type Document struct {
	Documentid int32         `json:"documentid"`
	Name       string        `json:"name"`
	CreatedAt  sql.NullTime  `json:"created_at"`
	Createdby  sql.NullInt32 `json:"createdby"`
}

type Normal struct {
	ID        int32         `json:"id"`
	Createdby sql.NullInt32 `json:"createdby"`
}

type User struct {
	ID        int32        `json:"id"`
	Username  string       `json:"username"`
	Password  string       `json:"password"`
	CreatedAt sql.NullTime `json:"created_at"`
}
