// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package DB

import (
	"context"
)

type Querier interface {
	CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error)
	CreateUsers(ctx context.Context, arg CreateUsersParams) (User, error)
	DeleteDocumentAdmin(ctx context.Context, documentid int32) error
	DeleteDocumentNormal(ctx context.Context, arg DeleteDocumentNormalParams) error
	//All Delete operations
	Deleteusers(ctx context.Context, id int32) error
	GetDocumentByCreatebyNormal(ctx context.Context, arg GetDocumentByCreatebyNormalParams) ([]Document, error)
	GetDocumentByID(ctx context.Context, documentid int32) (Document, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	// All Get operations
	GetUserByIDAndAdmin(ctx context.Context, id int32) (User, error)
	GetUserByNAME(ctx context.Context, username string) (User, error)
	// All Update operations
	UpdateUsers(ctx context.Context, arg UpdateUsersParams) error
}

var _ Querier = (*Queries)(nil)
